# Site settings
title: SINGLE THREAD
email: chanakyabhardwajj@gmail.com
description: Chanakya Bhardwaj's technical blog. Primarily Javascript & ES6 ramblings.
baseurl: ""
url: "https://chanakyabhardwajj.github.io"
github_username: chanakyabhardwajj
twitter_username: _chanakya

# Build settings
markdown: kramdown

#Outputting
permalink:     /:title
paginate_path: /page:num
