# Site settings
title: chanakya
email: chanakyabhardwajj@gmail.com
description: Chanakya Bhardwaj's technical blog. Javascript & ES6 ramblings.
baseurl: ""
url: "http://chanakyabhardwajj.com"
github_username: chanakyabhardwajj

# Build settings
markdown: kramdown

#Outputting
permalink:     /:title
paginate_path: /page:num
timezone:      null
